### ISSUE TITLE
PinterestApiV3Client eksik?

### ISSUE THREAD

**Issue by lencls37** [erdem-aksu/PinterestDesktopBot#1]
PinterestApiV3Client eksik? yardımcı olurmusun?
![image](https://user-images.githubusercontent.com/48754430/196006594-6240a8f2-520e-4b38-b32b-a392e95f9c45.png)

**Comment by erdem-aksu** [comment]
https://github.com/erdem-aksu/PinterestApi
Bu repoyu kullanabilirsin, build alındığında nuget paketi oluşuyor nuget.config dosyasına yukarıdaki reponun output dizinini eklersen öylede restore edebilir.
